# Generated by Django 4.1.7 on 2025-02-27 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('INCOME', 'Income Forecast'), ('EXPENSE', 'Expense Forecast'), ('CASHFLOW', 'Cash Flow Forecast')], max_length=50)),
                ('forecast_date', models.DateField()),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(choices=[('SAVING', 'Saving Tips'), ('BUDGET', 'Budget Adjustments'), ('INVESTMENT', 'Investment Options')], max_length=50)),
                ('advice_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('anomaly_type', models.CharField(choices=[('UNUSUAL_AMOUNT', 'Unusual Amount'), ('UNUSUAL_CATEGORY', 'Unusual Category'), ('UNUSUAL_FREQUENCY', 'Unusual Frequency')], max_length=50)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
